### ISSUE TITLE
Feature #1: User can look at a list of all Smash Ultimate characters

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to see a list of all Smash Ultimate characters as well as their name and number according to the official Nintendo website.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to scroll and view the Smash Ultimate fighter list on any device of their choosing
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90172283/156079022-255d91c0-8a2d-4c4a-b94c-e07aa5eafa5f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a basic html skeleton with a navbar and the smash ultimate background picture
- [x] Create a 'ul' in the html and fill it with dummy data
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Make sure entries look normal on mobile, tablet, and desktop
- [x] Create a 'data' object and populate it with all Smash Characters
- [x] Create a DOM tree for each character
  - [x] Populate the 'src' of the 'img's by using a template literal and concatenating it with the name of the character
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
