### ISSUE TITLE
Feature #2: User can view details of characters

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view details of characters
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Clicking on a character icon will allow the user to see a list of that character's stats, ie (move list name, frame data, etc).
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90172283/156083265-e973c270-4b57-459a-bfd3-953ef590ce2b.png)
![image](https://user-images.githubusercontent.com/90172283/156628526-b1144819-c61d-4869-921d-a643dbae36a8.png)
![image](https://user-images.githubusercontent.com/90172283/156628613-07aed94d-93ca-46c7-aa85-7ef458693817.png)
![image](https://user-images.githubusercontent.com/90172283/156083387-cbf4465c-bff1-4e73-a79c-1239a1a1145b.png)
![image](https://user-images.githubusercontent.com/90172283/156628663-bd548238-aef2-40c7-b497-c8e898d27cf7.png)
![image](https://user-images.githubusercontent.com/90172283/156628709-ba8e2961-9da8-4bd3-af07-ce23bde8fec3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal.
  - [x] Style the modal to the same theme as the character cards.
  - [x] Create a table with 3 columns and fill it with dummy data.
  - [x] Make sure the table scrolls.
  - [x] Make sure `img` and `h2` layouts are correct.
- [x] Make sure clicking on a character card shows it's details view.
  - [x] Make sure `$characterList` is hidden after clicking on a character.
  - [x] setup `data.currentCardIndex` to change to the current `data-card-id` of the card that is clicked.
- [x] Add a home icon to the navbar.
  - [x] Make the icon only show while viewing a character's data.
  - [x] add a listener to the home icon that hides the modal, hides home icon, and the character list view is shown.
  - [x] Make sure data.view switches back to 'characterList'.
  - [x] Make sure `data.currentCardIndex` switches back to null.
- [x] set up icon to hide the modal and go back to the character list when it's clicked.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
