### ISSUE TITLE
Feature #3: User can favorite characters

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now favorite characters.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While looking at a characters stats, the user will be able to click on a star to favorite that specific character.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90172283/156083821-15418bce-66fe-480a-8e3a-b3f568f31c55.png)
![image](https://user-images.githubusercontent.com/90172283/156083848-5414213b-9761-4fdc-a51e-42d0c13541a8.png)
![image](https://user-images.githubusercontent.com/90172283/156083860-211e5cb1-5881-4d45-aefa-e536d9021415.png)
![image](https://user-images.githubusercontent.com/90172283/156083875-e640bbad-dfbf-4549-bf7e-f71ed0f17c56.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a star on the same line as the Frame Data text.
- [x] Clicking the star should turn it yellow and mark that character as a favorite.
- [x] Add a star icon where the home button would be, but only make it show while on the 'character list' home screen view view.
- [x] Clicking the star should hide all character's in the list that aren't favorited.
- [x] If there are no favorited characters, tell the user.
- [x] The star should turn into the home icon and clicking that will show the full list of characters.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
