### ISSUE TITLE
Feature #5: User can delete their favorites

### ISSUE THREAD

**Issue by DreSean-Sutton** [DreSean-Sutton/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can now delete favorites from their list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

While looking at a character's data, the user will be able to click the star icon to delete a favorite from his list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90172283/156086400-b939bd28-523d-4ac6-bf02-d37b130917fb.png)
![image](https://user-images.githubusercontent.com/90172283/156086415-8aa3ad56-f7cd-4eb9-83c6-903c1c324d17.png)
![image](https://user-images.githubusercontent.com/90172283/156086428-2bb89ce3-ea7c-4c95-aebf-b18fcef78ab4.png)
![image](https://user-images.githubusercontent.com/90172283/156086456-e33f8666-f5ae-4cd0-a9d3-420de7d32e75.png)
![image](https://user-images.githubusercontent.com/90172283/156086294-3c4dd187-61a1-4512-8d86-4232fea9b092.png)
![image](https://user-images.githubusercontent.com/90172283/156086328-012be5fb-b36c-4549-aca8-042de5de88ea.png)
![image](https://user-images.githubusercontent.com/90172283/156086345-f4b4b865-191d-4803-be41-12867b4bf31f.png)
![image](https://user-images.githubusercontent.com/90172283/156086360-0d5598ee-6436-467b-8379-57cf2e98c55d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Clicking on a heart in the `character details` section will unfavorite that character if it was already favorited.
  - [x] Heart icon should change back to grey.
  - [x] Going to the favorites section should immediately remove that character from the favorites list.
- [x] Make it so hovering over Ness's heart in character details changes his name to 'Are you serious?'
- [x] Make it so favoriting Ness changes his heart color to black instead of pink
- [x] Add a property named `favoriteList` to `data` model and assign it the value of an empty array.
- [x] When a Character is favorited, they should be pushed into the `data.favoriteList` array.
- [x] When a character is unfavorited, they should be taken out of the `data.favoriteList` array.
- [x] Save favorited characters to their local storage.
- [x] Set it up so that favorited characters stay favorited even after refresh.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
